esphome:
  min_version: 2024.6.0
  name_add_mac_suffix: false

web_server:
  port: 80
  include_internal: true
  version: 3

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
